p8105_hw2_hq2229
================
Hantang Qin
2025-09-28

Problem1

Clean csv

``` r
# ---- P1: libraries ----
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(janitor)
```

    ## 
    ## 载入程序包：'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
library(lubridate)

# ---- 1A. pols-month.csv ----
pols <- read_csv("fivethirtyeight_datasets/pols-month.csv", show_col_types = FALSE) %>%
  separate(mon, into = c("year", "month_num", "day"), convert = TRUE) %>%
  mutate(
    month    = month.name[month_num],
    president = if_else(prez_gop == 1, "gop", "dem")
  ) %>%
  select(year, month, gov_gop, gov_dem, sen_gop, sen_dem, rep_gop, rep_dem, president)

# ---- 1B. snp.csv ----
snp <- read_csv("fivethirtyeight_datasets/snp.csv", show_col_types = FALSE) %>%
  mutate(date = mdy(date)) %>%                     # parse m/d/Y
  transmute(
    year  = year(date),
    month = as.character(month(date, label = TRUE, abbr = TRUE)),   # "Jan", "Feb", ...
    month = month.name[match(month, month.abb)],                    # -> "January" etc.
    close
  ) %>%
  arrange(year, match(month, month.name))

# ---- 1C. unemployment.csv ----
unemp <- read_csv("fivethirtyeight_datasets/unemployment.csv", show_col_types = FALSE) %>%
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month_abbr",
    values_to = "unemployment_rate"
  ) %>%
  mutate(
    month = month.name[match(month_abbr, month.abb)],
    year  = as.integer(Year)
  ) %>%
  select(year, month, unemployment_rate)

# ---- 1D. Join all three ----
final_data <- pols %>%
  left_join(snp,   by = c("year", "month")) %>%
  left_join(unemp, by = c("year", "month")) %>%
  arrange(year, match(month, month.name))

# ---- Quick descriptors for inline text ----
p1_n_obs   <- nrow(final_data)
p1_n_vars  <- ncol(final_data)
p1_yearmin <- min(final_data$year, na.rm = TRUE)
p1_yearmax <- max(final_data$year, na.rm = TRUE)
```

After cleaning and merging, the final monthly panel has **822
observations** and **11 variables**, spanning **1947–2015**.  
Key variables include political control (`president`, plus `gov_*`,
`sen_*`, `rep_*`), the **S&P closing value** (`close`), and the
**unemployment rate** (`unemployment_rate`).  
Putting everything in one tidy dataset makes it easy to line up
political changes with market and labor indicators over time.

Problem 2

``` r
### Problem 2 — Trash Wheel (my version, explicit ranges)

library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)

# Relative path (per HW)
trash_xlsx <- "202509 Trash Wheel Collection Data.xlsx"

# Mr. Trash Wheel
Mr_trash_wheel =
  read_excel(
    trash_xlsx,
    sheet = "Mr. Trash Wheel",
    range = "A2:N709"
  ) |>
  janitor::clean_names() |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    type = "Mr. Trash Wheel",
    year = as.character(year)
  ) |>
  select(date, type, everything(), -dumpster)

# Professor Trash Wheel
Professor_trash_wheel =
  read_excel(
    trash_xlsx,
    sheet = "Professor Trash Wheel",
    range = "A2:M134"
  ) |>
  janitor::clean_names() |>
  mutate(
    type = "Professor Trash Wheel",
    year = as.character(year)
  ) |>
  select(date, type, everything(), -dumpster)

# Gwynnda / Gwynns Falls Trash Wheel
# (use the sheet name in your file; if it's "Gwynnda Trash Wheel" instead, change here)
Gwynns_trash_wheel =
  read_excel(
    trash_xlsx,
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L351"
  ) |>
  janitor::clean_names() |>
  mutate(
    type = "Gwynnda Trash Wheel",
    year = as.character(year)
  ) |>
  select(date, type, everything(), -dumpster)

# Combine all three
trash_wheel =
  bind_rows(Mr_trash_wheel, Professor_trash_wheel, Gwynns_trash_wheel) |>
  arrange(date)

# --- Required summaries (used in inline R) ---
tw_n_obs      <- nrow(trash_wheel)
tw_n_devices  <- dplyr::n_distinct(trash_wheel$type)

tw_prof_total_tons <-
  Professor_trash_wheel |>
  summarise(total = sum(weight_tons, na.rm = TRUE)) |>
  pull(total) |>
  round(2)

# If the month column is month names, this works; if it's numeric, swap "June" for 6
tw_gwyn_jun22_cigs <-
  Gwynns_trash_wheel |>
  filter(year == "2022", month == "June") |>
  summarise(total = sum(cigarette_butts, na.rm = TRUE)) |>
  pull(total)
```

The cleaned dataset includes **1188 observations** from **3 trash
wheels**: Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda Trash
Wheel. Each entry records the device `type`, the `date`, and measures of
trash collected, including `weight_tons`, `volume_cubic_yards`, and
counts such as `plastic_bottles`, `polystyrene`, and `cigarette_butts`.
In terms of totals, **Professor Trash Wheel** has collected **282.26
tons** of trash overall. Meanwhile, **Gwynnda** picked up **18,120
cigarette butts** just in June 2022.

Problem 3

``` r
### Problem 3 — Zillow Rent Index (NYC)

library(tidyverse)
library(janitor)
library(lubridate)
library(stringr)
library(knitr)

# Borough map: county -> borough
borough_map <- c(
  "New York" = "Manhattan",
  "Kings"    = "Brooklyn",
  "Queens"   = "Queens",
  "Bronx"    = "Bronx",
  "Richmond" = "Staten Island"
)

# ---------------------------
# 1) ZIP reference
# ---------------------------
zip_ref <-
  read_csv("zillow_data/Zip Codes.csv", na = c("NA", ".", ""), show_col_types = FALSE) |>
  clean_names() |>
  mutate(
    zip_code = as.character(zip_code),
    county   = as.character(county)
  )

# ---------------------------
# 2) ZORI wide data (2015-01-31 .. 2024-08-31)
# ---------------------------
zori_raw <-
  read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv",
           na = c("NA", ".", ""), show_col_types = FALSE) |>
  clean_names() |>
  mutate(
    county_name = str_remove(county_name, " County$")
  ) |>
  # remove the leading "x" on date columns
  rename_with(~ str_remove(.x, "^x"), .cols = starts_with("x")) |>
  rename(zip_code = region_name, county = county_name) |>
  # keep rows that have at least one non-NA price across the date cols
  filter(!if_all(matches("^\\d{4}_\\d{2}_\\d{2}$"), is.na)) |>
  # keep identifiers + all date columns
  select(zip_code, county, any_of(c("region_id","size_rank")), matches("^\\d{4}_\\d{2}_\\d{2}$")) |>
  mutate(
    zip_code = as.character(zip_code),
    county   = as.character(county)
  )

# ---------------------------
# 3) Join + pivot longer  (SAFE SELECT)
# ---------------------------
joint_data <-
  right_join(zip_ref, zori_raw, by = c("zip_code","county")) |>
  pivot_longer(
    cols      = matches("^\\d{4}_\\d{2}_\\d{2}$"),
    names_to  = "date_chr",
    values_to = "price"
  ) |>
  mutate(
    date    = ymd(str_replace_all(date_chr, "_", "-")),
    borough = recode(county, !!!borough_map)
  ) |>
  select(any_of(c(
    "state","city","county","borough","state_fips","county_fips","county_code","metro",
    "neighborhood","zip_code","region_id","size_rank","date","price","file_date"
  ))) |>
  arrange(zip_code, date)

# ---------------------------
# 4) Descriptors (for inline R)
# ---------------------------
p3_n_obs          <- nrow(joint_data)
p3_n_zip          <- n_distinct(joint_data$zip_code)
p3_n_neighborhood <- n_distinct(joint_data$neighborhood)
p3_date_min       <- suppressWarnings(min(joint_data$date, na.rm = TRUE))
p3_date_max       <- suppressWarnings(max(joint_data$date, na.rm = TRUE))

# ---------------------------
# 5) ZIPs present in reference but missing in ZORI
# ---------------------------
zips_missing <- anti_join(
  zip_ref |> select(any_of(c("zip_code","county","neighborhood","city","state"))),
  zori_raw |> select(zip_code, county),
  by = c("zip_code","county")
)
n_missing_zips   <- nrow(zips_missing)
missing_examples <- head(zips_missing$zip_code, 5)

# ---------------------------
# 6) Largest drop: Jan 2020 → Jan 2021 (drop = 2020 − 2021)
# ---------------------------
drops_20_21 <-
  zori_raw |>
  transmute(
    zip_code, county,
    drop_2020_to_2021 = `2020_01_31` - `2021_01_31`
  ) |>
  filter(!is.na(drop_2020_to_2021)) |>
  left_join(zip_ref |> select(zip_code, any_of("neighborhood")), by = "zip_code") |>
  mutate(borough = recode(county, !!!borough_map))

top10_largest_drop <-
  drops_20_21 |>
  arrange(desc(drop_2020_to_2021)) |>
  select(zip_code, borough, neighborhood, county, drop_2020_to_2021) |>
  slice_head(n = 10)

# ---------------------------
# 7) Largest overall range across full period
# ---------------------------
top10_range <-
  joint_data |>
  group_by(zip_code) |>
  filter(any(!is.na(price))) |>
  summarise(
    price_max   = max(price, na.rm = TRUE),
    price_min   = min(price, na.rm = TRUE),
    price_range = price_max - price_min,
    .groups = "drop"
  ) |>
  arrange(desc(price_range)) |>
  slice_head(n = 10) |>
  left_join(zip_ref |> select(zip_code, any_of(c("neighborhood","county"))), by = "zip_code") |>
  mutate(borough = recode(county, !!!borough_map)) |>
  relocate(borough, neighborhood, county, .after = zip_code)

# ---------------------------
# 8) Output tables
# ---------------------------
kable(top10_largest_drop,
     caption = "Top 10 ZIP codes by largest ZORI drop (Jan 2020 → Jan 2021; drop = 2020 − 2021)")
```

| zip_code | borough   | neighborhood                  | county   | drop_2020_to_2021 |
|:---------|:----------|:------------------------------|:---------|------------------:|
| 10007    | Manhattan | Lower Manhattan               | New York |          912.5966 |
| 10069    | Manhattan | NA                            | New York |          748.1245 |
| 10009    | Manhattan | Lower East Side               | New York |          714.2550 |
| 10016    | Manhattan | Gramercy Park and Murray Hill | New York |          711.7045 |
| 10001    | Manhattan | Chelsea and Clinton           | New York |          710.4499 |
| 10002    | Manhattan | Lower East Side               | New York |          710.3028 |
| 10004    | Manhattan | Lower Manhattan               | New York |          705.9608 |
| 10038    | Manhattan | Lower Manhattan               | New York |          697.5853 |
| 10012    | Manhattan | Greenwich Village and Soho    | New York |          686.2218 |
| 10010    | Manhattan | Gramercy Park and Murray Hill | New York |          684.9304 |

Top 10 ZIP codes by largest ZORI drop (Jan 2020 → Jan 2021; drop = 2020
− 2021)

``` r
kable(zips_missing |> slice_head(n = 10),
     caption = "Examples: ZIPs present in ZIP file but missing from ZORI dataset")
```

| zip_code | county | neighborhood               |
|:---------|:-------|:---------------------------|
| 10464    | Bronx  | Southeast Bronx            |
| 10474    | Bronx  | Hunts Point and Mott Haven |
| 10475    | Bronx  | Northeast Bronx            |
| 10499    | Bronx  | NA                         |
| 10550    | Bronx  | NA                         |
| 10704    | Bronx  | NA                         |
| 10705    | Bronx  | NA                         |
| 10803    | Bronx  | NA                         |
| 11202    | Kings  | NA                         |
| 11224    | Kings  | Southern Brooklyn          |

Examples: ZIPs present in ZIP file but missing from ZORI dataset

``` r
kable(top10_range,
     caption = "Top 10 ZIP codes by overall ZORI range")
```

| zip_code | borough   | neighborhood               | county   | price_max | price_min | price_range |
|:---------|:----------|:---------------------------|:---------|----------:|----------:|------------:|
| 10007    | Manhattan | Lower Manhattan            | New York |  8422.624 |  5421.614 |    3001.010 |
| 10069    | Manhattan | NA                         | New York |  5926.113 |  3874.918 |    2051.196 |
| 10013    | Manhattan | Greenwich Village and Soho | New York |  5739.831 |  3794.151 |    1945.680 |
| 10014    | Manhattan | Greenwich Village and Soho | New York |  5032.078 |  3188.487 |    1843.591 |
| 10038    | Manhattan | Lower Manhattan            | New York |  4696.795 |  2875.616 |    1821.179 |
| 10011    | Manhattan | Chelsea and Clinton        | New York |  5228.192 |  3428.366 |    1799.826 |
| 10001    | Manhattan | Chelsea and Clinton        | New York |  5176.020 |  3377.574 |    1798.446 |
| 10004    | Manhattan | Lower Manhattan            | New York |  4223.940 |  2443.697 |    1780.243 |
| 10012    | Manhattan | Greenwich Village and Soho | New York |  4700.332 |  2942.344 |    1757.988 |
| 10282    | Manhattan | NA                         | New York |  7074.194 |  5349.640 |    1724.555 |

Top 10 ZIP codes by overall ZORI range

The final tidy dataset has **17284 observations** across **149 ZIP
codes** and **43 neighborhoods**, spanning **2015-01-31** to
**2024-08-31**. There are **174 ZIP codes** in the reference that don’t
appear in ZORI (e.g., 10464, 10474, 10475, 10499, 10550), likely PO-box
or non-residential areas. The largest pandemic-era drop (Jan 2020 → Jan
2021) and the widest overall range are shown in the tables above.

For the change between January 2020 and January 2021, the sharpest drop
in rental prices was about 912.5966 dollars in Lower Manhattan. Looking
over the entire time period, the largest overall decline was close to
3001.010 dollars, also in Lower Manhattan. Both patterns show how
dramatically the COVID-19 pandemic disrupted the rental market.
